using KrepostLib.Cryptography;

namespace KrepostWinForms.Middleware
{
    internal class CryptographyUtils
    {
        /// <summary>
        /// Generates a specific number of random bytes.
        /// </summary>
        /// <param name="bytes">The bumber of bytes to be generated.</param>
        /// <returns><see cref="byte"/>[] of generated bytes.</returns>
        public static byte[] GenerateSalt(int bytes)
        {
            return Generator.GenerateBytes(bytes);
        }
    }
}
